### ISSUE TITLE
What is the structure of Yolo V5 Generic Fusion?

### ISSUE THREAD

**Issue by 283pm** [sebastianvitterso/master-sau#3]
First of all, thank you for this great program.

I am a beginner and have some questions.

Regarding the network structure of generic fusion, is it correct that the RGB and Ir processes are fused just before the head?

Also, I was looking at the Tensorboard graph and I am a little confused. Is the output from SPPF being input to the first layer simply because the same processing that is used for SPPF is used for the output from SPPF as for the first input?

**Comment by sebastianvitterso** [comment]
> Regarding the network structure of generic fusion, is it correct that the RGB and Ir processes are fused just before the head?

This is correct, yes. To be more precise, the fusion happens right after the backbones, and all the skip paths also contain a fusion layer to allow for them to work. See our thesis figure below: 

![image](https://user-images.githubusercontent.com/37065184/189579635-5985d7fb-e4bd-404d-9e98-347a5515d003.png).

---

> Also, I was looking at the Tensorboard graph and I am a little confused. Is the output from SPPF being input to the first layer simply because the same processing that is used for SPPF is used for the output from SPPF as for the first input?

I'm not quite following, but that might be just because it's so early in the morning. Any chance the figure answers the question?

**Comment by 283pm** [comment]
Thank you for your fast reply.

My problem is solved by your great image.

Thank you.

**Comment by sebastianvitterso** [comment]
Good to hear! Good luck with your work.
